### ISSUE TITLE
Gereksinim belgesinin teslimati

### ISSUE THREAD

**Issue by ahmtylmz** [ahmtylmz/BBM487-20142-3#9]
Projenin ilk teslimatı olan gereksinim belgesi hazırlanıp kontrol ediltikten sonra teslim edilecektir. Bu belgenin hazırlanmasından tüm grup üyeleri sorumludur. 02.04.2015 tarihinde toplantı yapılacaktır. toplantı saattini grup konuşmasında bildireceğim. Toplantıda hazırlanan gereksinim belgesi baştan kontrol edlilip eksikleri tanımlanacaktır.

**Comment by ogzhnsbs** [comment]
Gereksinim belgesi kontrol edildi.
